name: AntiMineChat
version: ${pluginversion}
description: 'AntiMineChat'
website: 'http://wma.im'
main: im.wma.dev.amc.AntiMineChat
authors:
  - WMA
commands:
   amc:
      description: I have no idea
permissions:
    amc.allow:
        description: Allows a user to talk without moving
        default: op