name: AntiMineChat
version: 1.2-SNAPSHOT-dev-${maven.build.timestamp}
description: 'AntiMineChat'
website: 'http://wma.im'
main: im.wma.dev.amc.AntiMineChat
authors:
  - WMA
commands:
   amc:
      description: I have no idea
      usage: /<command> [player]
permissions:
    amc.allow:
        description: Allows a user to talk without moving
        default: op